### ISSUE TITLE
Custom track disappears when adding instance selection

### ISSUE THREAD

**Issue by mohmhm1** [rcsb/rcsb-saguaro-app#39]
I am trying to use the pfvselect function in conjunction with custom tracks. At first load, the custom tracks show up but toggling between other instances removes the custom tracks. I have an example of what I am trying to achieve and the issue here. 
https://codepen.io/mohmhm1/pen/OJEXeOR

**Comment by bioinsilico** [comment]
Thank you, @mohmhm1, for your question. I am so sorry for the long delay in replying. The best way to solve this issue is to use the `onChangeCallback` configuration [method](https://rcsb.github.io/rcsb-saguaro-app/interfaces/_internal_.InstanceSequenceConfig.html#onChangeCallback). 

```html
<html>
<head>
 <script src="https://cdn.jsdelivr.net/npm/@rcsb/rcsb-saguaro-app/build/dist/app.js" type="text/javascript"></script>
</head>
<body>
    <div id="pfvSelect" ></div>  
    <div id="pfv" style="margin-top:100px" ></div>
   <script> 
  RcsbFvWebApp.buildInstanceSequenceFv("pfv", "pfvSelect", "1A6D", {
    onChangeCallback: (context,module)=>{
        if(context.asymId == "A")
            module.getFv().addTrack({
                trackId: "blockTrack",
                trackHeight: 20,
                trackColor: "#F9F9F9",
                titleFlagColor: "#48a1b3",
                displayType: "block",
                displayColor: "#56e0f5",
                rowTitle: "COMPUTED",
                trackData: [{
                    begin:10,
                    end:100
                }]
            })
    }
});
</script>
</body>
</html>
```

Please, let me know if I can be of further help.

**Comment by bioinsilico** [comment]
@mohmhm1, I will close this issue. Please, feel free to reopen it if you have any questions.
